from .buy_game import buy_game
from .exit import exit
from .help import *
from .interface import *
from .kerangajaib import *
from .load import load
from .login import login
from .register import register
from .save import save
from .tambah_game import *
from .tictactoe import *
from .topup import topup
from .ubah_game import *
from .ubah_stok import ubah_stok
