from .load import load
from .save import save
from .register import register
from .login import login
from .exit import exit
from .ubah_stok import ubah_stok
from .help import *
from .kerangajaib import *
from .tictactoe import *
